# 토큰 유효기간, 키 지정
token:
  expriration_time: 86400000 #유효기간 1일 (ms)
  secret: '{cipher}AQB7uEYGJ/fIcJ2MkG3FyfphV3ME0tl2b56vwOj2hjfv2RtvJF4D6s6SpWN9I3PhNpXrKGY/773s53CG86U0OSAfMCfV+5nt9A1r4Ycu3Vs923LyT1OIJOi2gSqLMNJtoPo/8izlWG9APJrMkDoFAUC9UYgQ9QlDi7+QiaHARs3BpDmvH7AWRR95yTvFQQo1WOUWeNDR7GY9pGjRLj+U1C/Q7f7QEDLdkrlFfLkoeSplgUPJmrGSblthQqgXPm8RAmEQ5sNs5+C5Kp3+926umZqG+xjsJluhHMXF1UPPjlD5FosMaP9O8BwhLuWPOb3ou7lbhqAmM1itjh1JY9FR29vuba9f96niCLcT0nUJzxiJMESgRZrBmRd5Nt+Dzvt6FwU='

gateway:
  ip: 172.18.0.5 #docker의 gateway-service 주소
