server:
  port: 8761  #?????? ???? ???? ??

spring:
  application:
    name: discovery-service #고유 ID

#??? ??? ???? ???? ??? ?????
#???? ????? ???? ??
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
