server:
  port: 8888

spring:
  application:
    name: config-service
  #rabbitmq 설정
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        git:
#          uri: file://d:/Coding Practice/SpringCloudMSA
          # 도커에서 실행할 때
          uri: https://github.com/beeguriri/SpringCloudMSA
          # public repository 이므로 id/pw 필요 없음
        native:
          # http://127.0.0.1:8888/user-service/native 등으로 경로 반영 잘 됐는 지 확인
          # 로컬에서 실행할 때
#          search-locations: file:///${user.home}\Documents\native-file-repo

# actuator endpoint 추가
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
