server:
  port: 8888

spring:
  application:
    name: config-service
  #rabbitmq 설정
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        git:
#          uri: file://d:/Coding Practice/SpringCloudMSA
          uri: https://github.com/beeguriri/SpringCloudMSA

# actuator endpoint 추가
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
